language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.2.3"
cache: bundler
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:setup
script:
  - "bundle exec rake knapsack:rspec"
env:
  - CI_NODE_TOTAL=4 CI_NODE_INDEX=0
  - CI_NODE_TOTAL=4 CI_NODE_INDEX=1
  - CI_NODE_TOTAL=4 CI_NODE_INDEX=2
  - CI_NODE_TOTAL=4 CI_NODE_INDEX=3